### ISSUE TITLE
Describes schema's as YAML files

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#60]
In GitLab by @peterdesmet on Oct 1, 2020, 19:52

As I hoped, we can maintain our schemas as YAML files if we want:

```yaml
fields:
- name: media_id
  type: string
  format: default
  description: A unique identifier of a multimedia file within a project.
  example: M01
  constraints:
    required: true
    unique: true
- name: deployment_id
  type: string
  format: default
  description: The unique identifier of the deployment this observation belongs to. Foreign key to `deployment:deployment_id`.
  example: L01-D01
  constraints:
    required: true
```

These are a more readable and would allow for comments!

YAML files can be read natively by `frictionless-py` (see [here](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/target/describing-data/README.md#describing-schema)), but could also generate the json files each time we release a version. These could be stored in a `dist/` (distribution) directory.

@kbubnicki what do you think?
